const supabaseUrl='https://tynclkichqdswtofnvfi.supabase.co';const supabaseKey='sb_publishable_sH-Nodx2cIbQJADwbN4NRg_4lWe_cEm';const{createClient}=window.supabase;const supabaseClient=createClient(supabaseUrl,supabaseKey);let selectedProduct=null;let selectedPaymentMethod=null;let validatedNickname=null;let adminWhatsApp="6288901104271";async function loginDiscord(){const{error}=await supabaseClient.auth.signInWithOAuth({provider:'discord',options:{redirectTo:window.location.href}});if(error)console.error('Login error:',error);}
async function logout(){const{error}=await supabaseClient.auth.signOut();if(!error)window.location.reload();}
function toggleMenu(){document.getElementById('userDropdown').classList.toggle('show')}
async function checkUser(){const{data:{session}}=await supabaseClient.auth.getSession();const userArea=document.getElementById('user-area');if(session){const avatarUrl=session.user.user_metadata.avatar_url;userArea.innerHTML=`
            <div class="user-container" style="position: relative;">
                <div class="profile-pic" style="background-image: url('${avatarUrl}')" onclick="toggleMenu()"></div>
                <div id="userDropdown" class="user-dropdown">
                    <a href="transaksi.html" class="dropdown-item"><i class="fas fa-history" style="color:#3498db"></i> Riwayat Transaksi</a>
                    <div class="dropdown-item" onclick="logout()" style="color:#ff3b30"><i class="fas fa-sign-out-alt"></i> Keluar</div>
                </div>
            </div>`}else{userArea.innerHTML=`<button id="login-btn" class="btn-login" onclick="loginDiscord()">Login Discord</button>`}}
function switchTab(tabName){const topupContent=document.getElementById('topup-content');const ketContent=document.getElementById('keterangan-content');const buttons=document.querySelectorAll('.tab-switch button');topupContent.style.animation='none';ketContent.style.animation='none';void topupContent.offsetWidth;void ketContent.offsetWidth;if(tabName==='topup'){topupContent.style.display='block';ketContent.style.display='none';topupContent.style.animation='fadeIn 0.4s ease-in-out';buttons[0].classList.add('active');buttons[1].classList.remove('active')}else{topupContent.style.display='none';ketContent.style.display='block';ketContent.style.animation='fadeIn 0.4s ease-in-out';buttons[0].classList.remove('active');buttons[1].classList.add('active')}}
let typingTimer;let validatedAvatar=null;async function checkRobloxUser(username){try{const response=await fetch(`https://api.tokoardan.my.id/?username=${encodeURIComponent(username)}`);const data=await response.json();if(data&&data.success){return{success:!0,userId:data.userId,username:data.username,avatarUrl:data.avatarUrl}}else{return{success:!1,message:data.message||"User tidak ditemukan"}}}catch(error){console.error(error);return{success:!1,message:"Terjadi kesalahan koneksi"}}}
function checkNickname(){clearTimeout(typingTimer);const usernameInput=document.getElementById('userId');const username=usernameInput.value;const display=document.getElementById('nickname-display');const btnPesan=document.getElementById('btnPesan');if(username.length>2){display.style.display='flex';display.innerHTML=`<i class="fas fa-spinner fa-spin"></i> Mengecek Username...`;validatedNickname=null;validatedAvatar=null;typingTimer=setTimeout(async()=>{const result=await checkRobloxUser(username);if(result.success){validatedNickname=result.username;validatedAvatar=result.avatarUrl;display.className='nickname-box nickname-success';display.innerHTML=`
                    <img src="${result.avatarUrl}" 
                         style="width:40px;height:40px;border-radius:50%;margin-right:10px;">
                    ${result.username}
                `;if(selectedProduct){btnPesan.disabled=!1}}else{display.innerHTML=`<i class="fas fa-times-circle" style="color:red"></i> ${result.message}`;btnPesan.disabled=!0}},800)}else{display.style.display='none'}}
function selectItem(cardElement,productName,productPrice){if(cardElement.classList.contains('skeleton'))return;document.querySelectorAll('.item-card').forEach(card=>card.classList.remove('active'));cardElement.classList.add('active');selectedProduct={name:productName,rawPrice:productPrice};const fmtPrice=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',minimumFractionDigits:0}).format(productPrice);document.getElementById('selectedItemName').innerText=productName;document.getElementById('selectedItemPrice').innerText=fmtPrice;const btnPesan=document.getElementById('btnPesan');const display=document.getElementById('nickname-display');if(display.innerHTML.includes('Tidak Ditemukan')){btnPesan.innerHTML='ID Tidak Ditemukan? <i class="fas fa-question-circle" style="color:red"></i>';btnPesan.classList.add('btn-error');btnPesan.disabled=!0}else{btnPesan.innerHTML='Pesan Sekarang <i class="fas fa-chevron-right"></i>';btnPesan.classList.remove('btn-error');btnPesan.disabled=!1}}
function selectPayment(element,method){document.querySelectorAll('.payment-card').forEach(card=>card.classList.remove('active'));element.classList.add('active');selectedPaymentMethod=method;document.getElementById('payment-title').classList.remove('title-error');document.getElementById('payment-grid').classList.remove('shake-anim')}
function confirmOrder(){const userIdInput=document.getElementById('userId');const errorUser=document.getElementById('error-userId');let isIdValid=!0;if(!userIdInput.value){userIdInput.classList.add('error');if(errorUser)errorUser.style.display='block';isIdValid=!1}else{userIdInput.classList.remove('error');if(errorUser)errorUser.style.display='none'}
if(!isIdValid){document.getElementById('section-id').scrollIntoView({behavior:'smooth',block:'center'});return}
if(!selectedPaymentMethod){const paySection=document.getElementById('section-payment');const payTitle=document.getElementById('payment-title');const payGrid=document.getElementById('payment-grid');if(paySection)paySection.scrollIntoView({behavior:'smooth',block:'center'});if(payTitle)payTitle.classList.add('title-error');if(payGrid){payGrid.classList.remove('shake-anim');void payGrid.offsetWidth;payGrid.classList.add('shake-anim')}
return}
if(!selectedProduct)return;document.getElementById('conf-nick').innerText=validatedNickname||"Guest";document.getElementById('conf-id').innerText=userIdInput.value;document.getElementById('conf-item').innerText=selectedProduct.name;document.getElementById('conf-method').innerText=selectedPaymentMethod;document.getElementById('conf-price').innerText=document.getElementById('selectedItemPrice').innerText;document.getElementById('confirmModal').style.display='flex'}
function closeConfirmModal(){document.getElementById('confirmModal').style.display='none'}
async function processOrderToWA(){const userId=document.getElementById('userId').value;const{data:{session}}=await supabaseClient.auth.getSession();if(session){const{error}=await supabaseClient.from('transactions').insert([{user_id:session.user.id,game_name:'Roblox',item_name:selectedProduct.name,amount:selectedProduct.rawPrice,status:'pending'}]);if(error)console.error("Gagal simpan history:",error);}
const message=`Halo Admin KYRATOPUP, Saya mau order:
---------------------------
🎮 Game: Roblox
💎 Item: ${selectedProduct.name}
💰 Harga: ${document.getElementById('selectedItemPrice').innerText}
💳 Metode: ${selectedPaymentMethod}
🆔 Username: ${userId}
---------------------------
Mohon instruksi pembayaran, Terima kasih!`;const waLink=`https://wa.me/${adminWhatsApp}?text=${encodeURIComponent(message)}`;window.open(waLink,'_blank');closeConfirmModal()}
function showJokiModal(){document.getElementById('jokiModal').style.display='flex'}
function closeJokiModal(){document.getElementById('jokiModal').style.display='none'}
function processJokiWA(){const message=`Halo Admin KYRATOPUP,\nSaya tertarik untuk memesan layanan *JOKI ROBLOX* 🔥\n\nMohon info detail paket dan harganya ya Min. Terima kasih!`;const waLink=`https://wa.me/${adminWhatsApp}?text=${encodeURIComponent(message)}`;window.open(waLink,'_blank');closeJokiModal()}
function startPersistentTimer(){const timerDisplay=document.getElementById('countdown');const flashSection=document.getElementById('flash-sale-container');const targetDate=new Date(2025,1,25,23,59,59).getTime();const timerInterval=setInterval(()=>{const now=new Date().getTime();const distance=targetDate-now;if(distance<0){clearInterval(timerInterval);timerDisplay.innerHTML="EXPIRED";if(flashSection)flashSection.style.display='none';return}
const d=Math.floor(distance/(1000*60*60*24));const h=Math.floor((distance%(1000*60*60*24))/(1000*60*60));const m=Math.floor((distance%(1000*60*60))/(1000*60));const s=Math.floor((distance%(1000*60))/1000);timerDisplay.innerHTML=`${d>0 ? d+'d ' : ''}${h<10?'0'+h:h} : ${m<10?'0'+m:m} : ${s<10?'0'+s:s}`},1000)}
document.addEventListener('DOMContentLoaded',()=>{checkUser();startPersistentTimer();setTimeout(showJokiModal,2000);const allCards=document.querySelectorAll('.item-card');allCards.forEach(card=>card.classList.add('skeleton'));setTimeout(()=>{allCards.forEach(card=>card.classList.remove('skeleton'))},5000);window.addEventListener('click',function(e){const dropdown=document.getElementById('userDropdown');const profilePic=document.querySelector('.profile-pic');if(dropdown&&profilePic&&!dropdown.contains(e.target)&&!profilePic.contains(e.target)){dropdown.classList.remove('show')}})})